### ISSUE TITLE
installing tree-sitter.dev~ is super slow

### ISSUE THREAD

**Issue by aryx** [returntocorp/ocaml-tree-sitter-semgrep#166]
make setup, and some of our jobs in CI take a long time partly because of the 'install tree-sitter.dev~' step.
Is there something we can do to speedup that step? Why is it so slow?

**Comment by mjambon** [comment]
Is this still the case? Are you referring to ocaml-tree-sitter CI or semgrep CI? Which jobs?

**Comment by aryx** [comment]
I was referring to 'make setup' when done locally on my linux (or macbook) machine in semgrep, or semgrep CI.

If you do 'make setup' in semgrep/, the step below takes more than 5 minutes (all the rest is pretty fast):
```
tree-sitter.~dev] no changes from git+file:///home/pad/github/semgrep/ocaml-tree-sitter#HEAD
The following actions will be performed:
  ∗ install tree-sitter ~dev*
Processing  1/1: [tree-sitter.~dev: git]
```
Not sure what is doing OPAM here. Seems busy with calls to 'git' and 'git-remote-http' when using top to see the list of processes.
Maybe we could use again some git shallow clone somewhere to speedup things.

In fact it is so slow, and because it does not even show any progress bad, I think a user could be very tempted to interrupt 'make setup' (I know I did in the past).

**Comment by mjambon** [comment]
This problem will go away when I'm done with #204
