### ISSUE TITLE
Add ocaml-tree-sitter to opam

### ISSUE THREAD

**Issue by mjambon** [returntocorp/ocaml-tree-sitter-semgrep#181]
Ocaml-tree-sitter has been used in [semgrep](https://github.com/returntocorp/semgrep). So far we haven't done much work toward making releases for public use. It would be useful for OCaml programmers to get an easier access to the OCaml executables (`ocaml-tree-sitter`, `simplify-grammar`) and to the runtime library. Proper versioning would help users track incompatibilities and manage upgrades better (e.g. when the type of parsing errors changes in the runtime library).

At first glance, opam should install the following:
* the code generators `ocaml-tree-sitter`, `simplify-grammar` etc.
* the runtime library

These ideally should be two separate packages, since code generators are not necessary once the OCaml code has been generated.

Additionally, we have shell scripts like `gen-c` and `gen-ocaml` which are used for generating various files from templates so as to produce a valid dune subproject, such as e.g. https://github.com/returntocorp/semgrep-ruby. I'm not sure how much of the shell scripts should be included in an opam package or whether they would needed to be adapted for more general use. At least, the executables installed by opam should have a sufficiently unique name.

To get started with an opam package, we need at least:
* a version: create a version file so as to make the version available with `ocaml-tree-sitter --version`, tag git commits with the version e.g. `git tag v1.2.3`.
* install all the things that are needed to get from a tree-sitter-XXX project to a dune-ready folder
* mark the package as experimental

Later we can work on renaming/hiding the scripts or having one main command with multiple subcommands.

**Comment by joseeMDS** [comment]
Since `gen-c` and `gen-ocaml` are essential scripts in the workflow to generate and organize some files i think it would be nice to adapt them, maybe something like `ocaml-tree-sitter --generate`?

Also improving error messages is important, while trying it i had no idea what `Error: Aliases are not suported` meaned, maybe turn it more explicative like `Error: Aliases are not suported, use simplify-grammar and try again with the new generated file`, although adding `gen-c` to the workflow would make this not necessary, would still be useful.

Other thing that would be useful is something like [conf-pkg-config](https://opam.ocaml.org/packages/conf-pkg-config/) for tree-sitter

**Comment by mjambon** [comment]
I created issues for subcommands and for better error messages. Regarding pkg-config, I forgot what the situation is. I'll let you take care of it unless you need me.

**Comment by aryx** [comment]
We also need to fix the segfault in bindings.c

**Comment by mjambon** [comment]
@joseeMDS @aryx is referring to #173.

**Comment by joseeMDS** [comment]
Nice, what should be the version of the project?

**Comment by mjambon** [comment]
`0.x.x` would indicate there's no compatibility guarantees from one version to the next. `1.0.0` on the other hand requires us to maintain backward compatibility i.e. not break user's code when they upgrade to a greater `1.x.x` (according to the [semver](https://semver.org/) rules). Since we're planning to change the command line, let's start with `0.0.0`. The next version would be `0.1.0`, and we'll switch to `1.0.0` when we're happy with the basic command-line interface.

**Comment by joseeMDS** [comment]
fine! ATM im finishing my PR for melange, but when i finish it i will focus here

**Comment by stroxler** [comment]
We're looking into options for adding error-tolerant parsing to the [Pyre type checker](https://github.com/facebook/pyre-check) sometime this year, with a primary goal of having a parser that's useful for autocomplete.

One option we'd like to consider is using tree-sitter for this. Having ocaml-tree-sitter in opam isn't a hard blocker for this, but it would probably make it easier.

Is this something you could use help with? In the meantime we may try setting up a toy repository to learn how to use the tool.

**Comment by aryx** [comment]
I think @mjambon actually created a different repository, ocaml-tree-sitter-lang whose primary goal is to be used by the OCaml community. ocaml-tree-sitter-semgrep has lots of stuff specifics to semgrep that does not make sense in the Pyre context for example.

**Comment by stroxler** [comment]
My impression from a skim (I'll admit I got a bit lost) was that the `ocaml-tree-sitter-lang` repo had been split into separate per-language repos such as https://github.com/returntocorp/semgrep-python, and that the underlying code generators live here

We could probably rely on semgrep-python for a first test, but:
(a) semgrep-python has a bit of extra semgrep-specific syntax we don't need
(b) there's a chance pyre may want to modify the grammar (for very similar reasons to why semgrep does: our Pysa static analyzer has a DSL with slightly different syntax)

Both these factors may mean we need our own slightly different grammar, which I suspect will require a separate codegen step.

**Comment by aryx** [comment]
@mjambon @joseemds what is the current status of making an OPAM release for ocaml-tree-sitter-core?

**Comment by mjambon** [comment]
I think we should close the issue to avoid misguiding people. ocaml-tree-sitter isn't simple. It includes a bunch of shell scripts, javascript, C, and a pipeline involving grammar extensions and tests. Then there's the big issue that code generation (`tree-sitter generate`) takes a long time (seconds to minutes) and therefore is unreasonable to run each time we want to recompile a project. Also, many users aren't particularly interested in making their own tree-sitter parsers but rather just using parsers that were written for various programming languages. Those users may be interested in having the generated parsers in opam, I'm not sure. Right now, the idea is that the parsers for various languages are maintained from the [ocaml-tree-sitter-languages repo](https://github.com/returntocorp/ocaml-tree-sitter-languages). We're not using it for semgrep because semgrep extends the original parsers but instead we use the [ocaml-tree-sitter-semgrep repo](https://github.com/returntocorp/ocaml-tree-sitter-semgrep).

**Comment by mjambon** [comment]
@stroxler as noted in my comment above, the whole ocaml-tree-sitter pipeline isn't ready to be put into opam and I don't think it's a blocker for anyone. However, I think it could be nice to publish the parsers generated in [ocaml-tree-sitter-languages](https://github.com/returntocorp/ocaml-tree-sitter-languages) to opam. This would result in a collection of language parsers, each with its own opam package. I'll open an issue there.
